"""Create CareerSuggestions table

Revision ID: 1b4cfca53b52
Revises: e0e32eba5ac2
Create Date: 2025-02-18 16:50:10.581996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b4cfca53b52'
down_revision = 'e0e32eba5ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('career_suggestions',
    sa.Column('CSid', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('exerciseid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exerciseid'], ['exercise.exerciseid'], ),
    sa.PrimaryKeyConstraint('CSid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('career_suggestions')
    # ### end Alembic commands ###
