"""Added CareerPath, CareerQuestion, CareerStory, IndustryChallenge tables

Revision ID: 1b73361468ea
Revises: 1b4cfca53b52
Create Date: 2025-02-20 17:40:08.564680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b73361468ea'
down_revision = '1b4cfca53b52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('career_path',
    sa.Column('CPid', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('exerciseid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exerciseid'], ['exercise.exerciseid'], ),
    sa.PrimaryKeyConstraint('CPid')
    )
    op.create_table('career_question',
    sa.Column('CQid', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('yes_answer', sa.String(length=255), nullable=False),
    sa.Column('no_answer', sa.String(length=255), nullable=False),
    sa.Column('careerpathid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['careerpathid'], ['career_path.CPid'], ),
    sa.PrimaryKeyConstraint('CQid')
    )
    op.create_table('career_story',
    sa.Column('CSid', sa.Integer(), nullable=False),
    sa.Column('story', sa.Text(), nullable=False),
    sa.Column('careerpathid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['careerpathid'], ['career_path.CPid'], ),
    sa.PrimaryKeyConstraint('CSid')
    )
    op.create_table('industry_challenge',
    sa.Column('ICid', sa.Integer(), nullable=False),
    sa.Column('challenge_text', sa.Text(), nullable=False),
    sa.Column('careerpathid', sa.Integer(), nullable=False),
    sa.Column('example_solution', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['careerpathid'], ['career_path.CPid'], ),
    sa.PrimaryKeyConstraint('ICid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('industry_challenge')
    op.drop_table('career_story')
    op.drop_table('career_question')
    op.drop_table('career_path')
    # ### end Alembic commands ###
