"""Added UserModuleProgress table

Revision ID: 2e9063fe9a1c
Revises: 8218bc72475e
Create Date: 2025-01-30 15:19:19.355852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e9063fe9a1c'
down_revision = '8218bc72475e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_module_progress',
    sa.Column('UMPid', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('moduleid', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('locked', 'in progress', 'completed', name='progress_status'), nullable=True),
    sa.ForeignKeyConstraint(['moduleid'], ['module.moduleid'], ),
    sa.ForeignKeyConstraint(['userid'], ['user.userid'], ),
    sa.PrimaryKeyConstraint('UMPid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_module_progress')
    # ### end Alembic commands ###
