"""Added solution_text column to Solution table

Revision ID: 4da5b037e6ae
Revises: a5f4378143e4
Create Date: 2025-02-05 18:28:59.126881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4da5b037e6ae'
down_revision = 'a5f4378143e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solution', schema=None) as batch_op:
        batch_op.add_column(sa.Column('solution_text', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solution', schema=None) as batch_op:
        batch_op.drop_column('solution_text')

    # ### end Alembic commands ###
