"""Added UserModuleProgress table

Revision ID: 539acdbe52b4
Revises: a418bedbd014
Create Date: 2025-01-30 16:22:11.465998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '539acdbe52b4'
down_revision = 'a418bedbd014'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_module_progress',
    sa.Column('UMPid', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('moduleid', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('locked', 'available', 'completed', name='progress_status'), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['moduleid'], ['module.moduleid'], ),
    sa.ForeignKeyConstraint(['userid'], ['user.userid'], ),
    sa.PrimaryKeyConstraint('UMPid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_module_progress')
    # ### end Alembic commands ###
