"""Removed status column from Exercise table

Revision ID: 782cc13f5af2
Revises: 4da5b037e6ae
Create Date: 2025-02-06 20:28:32.878744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '782cc13f5af2'
down_revision = '4da5b037e6ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=9), nullable=True))

    # ### end Alembic commands ###
