"""Added Exercise table

Revision ID: 8218bc72475e
Revises: 57c885fd3196
Create Date: 2025-01-30 15:14:46.516219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8218bc72475e'
down_revision = '57c885fd3196'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise',
    sa.Column('exerciseid', sa.Integer(), nullable=False),
    sa.Column('moduleid', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('solution', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('locked', 'available', 'completed', name='exercise_status'), nullable=True),
    sa.ForeignKeyConstraint(['moduleid'], ['module.moduleid'], ),
    sa.PrimaryKeyConstraint('exerciseid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exercise')
    # ### end Alembic commands ###
