"""Added CareerStory table

Revision ID: 91e4161ff34a
Revises: 9d53aed6c7eb
Create Date: 2025-03-06 16:14:34.998719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91e4161ff34a'
down_revision = '9d53aed6c7eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('career_story',
    sa.Column('CStoryid', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('exerciseid', sa.Integer(), nullable=True),
    sa.Column('CSid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['CSid'], ['career_suggestions.CSid'], ),
    sa.ForeignKeyConstraint(['exerciseid'], ['exercise.exerciseid'], ),
    sa.PrimaryKeyConstraint('CStoryid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('career_story')
    # ### end Alembic commands ###
