"""Removed CareerQuestion table

Revision ID: 977b94436ef7
Revises: deca97e6bfc1
Create Date: 2025-03-03 18:17:38.353286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '977b94436ef7'
down_revision = 'deca97e6bfc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('career_question')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('career_question',
    sa.Column('CQid', sa.INTEGER(), nullable=False),
    sa.Column('question', sa.TEXT(), nullable=False),
    sa.Column('yes_answer', sa.VARCHAR(length=255), nullable=False),
    sa.Column('no_answer', sa.VARCHAR(length=255), nullable=False),
    sa.Column('careersuggid', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['careersuggid'], ['career_suggestions.CSid'], ),
    sa.PrimaryKeyConstraint('CQid')
    )
    # ### end Alembic commands ###
