"""Added IndustryChallenge table

Revision ID: 97fcbb590663
Revises: af55c0c3b22d
Create Date: 2025-03-03 18:23:19.723258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97fcbb590663'
down_revision = 'af55c0c3b22d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('industry_challenge',
    sa.Column('ICid', sa.Integer(), nullable=False),
    sa.Column('challenge_text', sa.Text(), nullable=False),
    sa.Column('exerciseid', sa.Integer(), nullable=False),
    sa.Column('example_solution', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['exerciseid'], ['exercise.exerciseid'], ),
    sa.PrimaryKeyConstraint('ICid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('industry_challenge')
    # ### end Alembic commands ###
