"""Added solution_regex column to Solution table

Revision ID: 9a902c746af6
Revises: c8d8c61bf4e0
Create Date: 2025-02-05 18:16:09.593289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a902c746af6'
down_revision = 'c8d8c61bf4e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solution', schema=None) as batch_op:
        batch_op.add_column(sa.Column('solution_regex', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solution', schema=None) as batch_op:
        batch_op.drop_column('solution_regex')

    # ### end Alembic commands ###
