"""Added default_code column to IndustryChallenge table

Revision ID: 9d53aed6c7eb
Revises: 97fcbb590663
Create Date: 2025-03-04 16:43:58.374802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d53aed6c7eb'
down_revision = '97fcbb590663'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('industry_challenge', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_code', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('industry_challenge', schema=None) as batch_op:
        batch_op.drop_column('default_code')

    # ### end Alembic commands ###
