"""Removed solution_text column from Solution table

Revision ID: a5f4378143e4
Revises: 791ff547a99f
Create Date: 2025-02-05 18:27:58.349394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5f4378143e4'
down_revision = '791ff547a99f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solution', schema=None) as batch_op:
        batch_op.drop_column('solution_text')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solution', schema=None) as batch_op:
        batch_op.add_column(sa.Column('solution_text', sa.TEXT(), nullable=False))

    # ### end Alembic commands ###
