"""Removed IndustryChallenge table

Revision ID: af55c0c3b22d
Revises: d1af2b6f634e
Create Date: 2025-03-03 18:19:29.726449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af55c0c3b22d'
down_revision = 'd1af2b6f634e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('industry_challenge')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('industry_challenge',
    sa.Column('ICid', sa.INTEGER(), nullable=False),
    sa.Column('challenge_text', sa.TEXT(), nullable=False),
    sa.Column('careersuggid', sa.INTEGER(), nullable=False),
    sa.Column('example_solution', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['careersuggid'], ['career_suggestions.CSid'], ),
    sa.PrimaryKeyConstraint('ICid')
    )
    # ### end Alembic commands ###
