"""Removed solution column from Exzercise table

Revision ID: b1e51654b734
Revises: bafd14fce116
Create Date: 2025-02-05 17:35:27.337383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1e51654b734'
down_revision = 'bafd14fce116'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.drop_column('solution')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.add_column(sa.Column('solution', sa.TEXT(), nullable=False))

    # ### end Alembic commands ###
