"""Create Solution table

Revision ID: c8d8c61bf4e0
Revises: b1e51654b734
Create Date: 2025-02-05 17:39:36.663791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8d8c61bf4e0'
down_revision = 'b1e51654b734'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solution',
    sa.Column('solutionid', sa.Integer(), nullable=False),
    sa.Column('exerciseid', sa.Integer(), nullable=False),
    sa.Column('solution_text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['exerciseid'], ['exercise.exerciseid'], ),
    sa.PrimaryKeyConstraint('solutionid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('solution')
    # ### end Alembic commands ###
