"""Removed CareerStory table

Revision ID: d1af2b6f634e
Revises: 977b94436ef7
Create Date: 2025-03-03 18:18:34.929422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1af2b6f634e'
down_revision = '977b94436ef7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('career_story')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('career_story',
    sa.Column('CSid', sa.INTEGER(), nullable=False),
    sa.Column('story', sa.TEXT(), nullable=False),
    sa.Column('careersuggid', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['careersuggid'], ['career_suggestions.CSid'], ),
    sa.PrimaryKeyConstraint('CSid')
    )
    # ### end Alembic commands ###
