"""Added keyresponsibilities column to CareerSuggestions table

Revision ID: deca97e6bfc1
Revises: 50a0818235f6
Create Date: 2025-02-28 17:22:31.816594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'deca97e6bfc1'
down_revision = '50a0818235f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('career_suggestions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('keyresponsibilities', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('career_suggestions', schema=None) as batch_op:
        batch_op.drop_column('keyresponsibilities')

    # ### end Alembic commands ###
