"""Added expected_outputcolumn to Solution model

Revision ID: e0e32eba5ac2
Revises: 2c59a0d33c26
Create Date: 2025-02-18 11:31:30.700536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0e32eba5ac2'
down_revision = '2c59a0d33c26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solution', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expected_output', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solution', schema=None) as batch_op:
        batch_op.drop_column('expected_output')

    # ### end Alembic commands ###
