"""Updated module status values

Revision ID: e3f1f4415396
Revises: ae78aada3a6d
Create Date: 2025-01-30 15:55:28.107657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3f1f4415396'
down_revision = 'ae78aada3a6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_exercise_progress', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.Enum('locked', 'available', 'completed', name='exercise_progress_status'),
               existing_nullable=True)

    with op.batch_alter_table('user_module_progress', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.Enum('locked', 'available', 'completed', name='progress_status'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_module_progress', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('locked', 'available', 'completed', name='progress_status'),
               type_=sa.VARCHAR(length=11),
               existing_nullable=True)

    with op.batch_alter_table('user_exercise_progress', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('locked', 'available', 'completed', name='exercise_progress_status'),
               type_=sa.VARCHAR(length=11),
               existing_nullable=True)

    # ### end Alembic commands ###
