"""Added UserExerciseProgress table

Revision ID: f8826c208e71
Revises: 2e9063fe9a1c
Create Date: 2025-01-30 15:21:21.826486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8826c208e71'
down_revision = '2e9063fe9a1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_exercise_progress',
    sa.Column('UEPid', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('exerciseid', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('locked', 'in progress', 'completed', name='exercise_progress_status'), nullable=True),
    sa.ForeignKeyConstraint(['exerciseid'], ['exercise.exerciseid'], ),
    sa.ForeignKeyConstraint(['userid'], ['user.userid'], ),
    sa.PrimaryKeyConstraint('UEPid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_exercise_progress')
    # ### end Alembic commands ###
